/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hwdtqbgqfxjqreelrsym"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3ZHRxYmdxZnhqcXJlZWxyc3ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxOTM5MTIsImV4cCI6MjA3Nzc2OTkxMn0.j4-nwODfjuHqCxx-mzaM_rAl4WFbJSWxFtvLOPTd-xc"